version: '3.8'

services:
  backend:
    build:
      context: ./flask_backend
      dockerfile: Dockerfile-backend
    container_name: auction_backend
    env_file:
      - ./flask_backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./flask_backend:/app
    networks:
      - auction_network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile-frontend
    container_name: react_frontend
    env_file:
      - ./react-frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - auction_network

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: auction_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - auction_network

networks:
  auction_network:
    driver: bridge

volumes:
  mongo_data:
