version: '3.1'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    links:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
