version: '3.8'

services:
  backend:
    build:
      context: /flask_backend
      dockerfile: Dockerfile-backend
    container_name: auction_backend
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./flask_backend:/app
    networks:
      - auction_network

  frontend:
    build:
      context: /react-frontend
      dockerfile: Dockerfile-frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: auction_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - auction_network

networks:
  auction_network:

volumes:
  mongo_data:





